### ISSUE TITLE
Typescript dynamic show static name

### ISSUE THREAD

**Issue by phunguyen19** [adaltas/node-http-status#30]
I tried to use dynamic loading `status['500_CODE']` but got this error.

![](https://image.ibb.co/dhhF7q/Screen-Shot-2018-11-13-at-1-09-32-PM.png)
![](https://image.ibb.co/iOkDtV/Screen-Shot-2018-11-13-at-1-09-43-PM.png)

**Comment by wdavidw** [comment]
Hi, I have just entirely re-written the TypeScript definition file. I am no expert in TypeScript so I welcome any feedback in this manner. A new version is published with an associated test file. Feel free to re-open if it doesn't solve your issue.

**Comment by phunguyen19** [comment]
@wdavidw Thanks for your support. The issue is solved.
