### ISSUE TITLE
TypeScript Support Missing in http-status v1.8.0

### ISSUE THREAD

**Issue by checkiamsiam** [adaltas/node-http-status#52]
Describe the bug

In version 1.8.0 of the http-status package, TypeScript support has been removed. The previous versions included TypeScript definitions, making it easy to use the package in TypeScript projects. Additionally, the separate TypeScript definition package (@types/http-status) has been deprecated, leaving no official TypeScript support for the package.

To Reproduce

The issue can be reproduced by attempting to use the http-status package in a TypeScript project with the latest version (1.8.0). Below is a minimal example:

```
Copy code
import { StatusCodes } from 'http-status';


const statusCode: number = StatusCodes.OK;
console.log(`Status code is ${statusCode}`);
```

When trying to compile this TypeScript code, it results in errors due to missing type definitions.

Additional context

The lack of TypeScript support in the latest version breaks compatibility for existing TypeScript projects using http-status. Previously, it was possible to use the built-in TypeScript definitions or rely on the separate @types/http-status package, but with the latter now deprecated, there is no official TypeScript support.

**Comment by wdavidw** [comment]
Hi, TypeScript support wasn't removed in version 1.8.0. Indeed, the package is rewritten in TypeScript. It must be a path which is invalid with the new build.

The package.json file looks coherent to me:

```json
{
 ...
  "exports": {
    ".": {
      "import": "./dist/index.js",
      "types": "./dist/index.d.ts",
      "require": "./dist/index.cjs"
    },
    "./*": {
      "import": "./dist/*.js",
      "types": "./dist/*.d.ts",
      "require": "./dist/*.cjs"
    }
  },
  "files": [
    "dist"
  ],
}
```

Seems like you are using ESM, was is your node.js version. I will look into it tomorrow.

**Comment by wdavidw** [comment]
OK, this is related to the import. Updating your code to `import status from "http-status";` shall work as expected. Version 1.8.0 shall have been a major release, I messed up with the release command, see #51

**Comment by checkiamsiam** [comment]
See.

![image](https://github.com/user-attachments/assets/eb5617f7-6a56-42e1-b547-83e5ed422f02)

**Comment by Code-Divine** [comment]
Huge fuck up. revert 1.8.0 as it was and release the changes as new version.

**Comment by wdavidw** [comment]
This is the plan

**Comment by wdavidw** [comment]
Two new versions are published:
- version 1.8.1 fixes 1.8.0 and is a copy of the previous version 1.7.4
- version 2.0.0 is the new version with the convertions to ESM and TypeScript

**Comment by nickheyer** [comment]
The level of disaster this has caused...

**Comment by wdavidw** [comment]
Keep in mind, this is open source volunteer work, we do it in our free time.

**Comment by nickheyer** [comment]
I don't think anyone is blaming you specifically, this is a systemic issue.
